name: Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Rename APK
        run: |
          APK_PATH=$(find app/build/outputs/apk/release -name "*.apk")
          VERSION=${GITHUB_REF#refs/tags/v}
          mv $APK_PATH app/build/outputs/apk/release/pyholex-v$VERSION.apk

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/pyholex-*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}